config/routes.rb
Kogo::Application.routes.draw do

  resources :channels do
    resources :messages
  end
  
  devise_for :users

  root :to => "channels#index"

end

begin
  Rails.application.routes.draw do
    bushido_routes
  end
rescue => e
  puts "Error loading the Bushido routes:"
  puts "#{e.inspect}"
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :messages, :dependent => :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :bushido_authenticatable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def bushido_extra_attributes(extra_attributes)
    self.name = extra_attributes["first_name"] + extra_attributes["last_name"]
    self.name = extra_attributes["email"].split("@").first if self.name.length == 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  before_filter :authenticate_user!
  
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel  = Channel.find(params[:id])
    @messages = Message.includes(:user).limit(5).order("created_at DESC").reverse

    # don't use #build. it adds the new message to the list of messages channel already has
    @message = Message.new :channel_id => @channel.id
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :ok }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout false
  
  before_filter :authenticate_user!

  # GET /messages
  # GET /messages.json
  def index
    if params[:last_message_id]
      @messages = Message.includes(:user).where("id > ?", params[:last_message_id])
    else
      @messages = Message.includes(:user).limit(5).order(:created_at).reverse_order
    end

    @message_data = []
    @messages.each do |message|
      @message_data.push({
          :id => message.id,
          :user => message.user.name,
          :content => message.content
        })
    end
    
    respond_to do |format|
      format.json { render :json => @message_data}
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.user_id = current_user.id
    
    respond_to do |format|
      if @message.save
        format.json { render json: @message, status: :created}
      else
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/channels/_form.html.haml
= form_for @channel do |f|
  -if @channel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@channel.errors.count, "error")} prohibited this channel from being saved:"
      %ul
        - @channel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name

  .actions
    = f.submit 'Save'

app/views/channels/edit.html.haml
%h1 Editing channel

= render 'form'

= link_to 'Show', @channel
\|
= link_to 'Back', channels_path

app/views/channels/index.html.haml
%h1 Listing channels

%table
  %tr
    %tr name
    %th
    %th
    %th
      
  - @channels.each do |channel|
    %tr
      %td= channel.name
      %td= link_to 'Show', channel
      %td= link_to 'Edit', edit_channel_path(channel)
      %td= link_to 'Destroy', channel, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Channel', new_channel_path

app/views/channels/new.html.haml
%h1 New channel

= render 'form'

= link_to 'Back', channels_path

app/views/channels/show.html.haml
- content_for :header do
  :javascript
    $.data(document, 'channel_id',      #{@channel.id})
    $.data(document, 'last_message_id', #{@messages.last.id})

%audio{:class => "audio_stage"}

.messages
  - @messages.each do |message|
    .message
      = message.user.name
      \:
      = message.content

=form_for([@channel, @message], :remote => true) do |f|  
  =f.hidden_field :channel_id, :value =>  @message.channel_id
  =f.text_field :content
  =f.submit

= link_to 'Edit', edit_channel_path(@channel)
\|
= link_to 'Back', channels_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kogo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield :header %>

</head>
<body>

<%- if user_signed_in? %>
  <%= link_to "logout", destroy_user_session_path, :method => :delete %>
<%- end %>

<%= yield %>

</body>
</html>